# Generated by Django 2.2.2 on 2019-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_auto_20191110_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
