# Generated by Django 2.2.2 on 2019-11-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_proveedor_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
